package api

import (
	context "context"
	fmt "fmt"
	gorm1 "github.com/infobloxopen/atlas-app-toolkit/v2/gorm"
	resource "github.com/infobloxopen/atlas-app-toolkit/v2/gorm/resource"
	errors "github.com/infobloxopen/protoc-gen-gorm/errors"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	gorm "gorm.io/gorm"
	strings "strings"
	time "time"
)

type TransectORM struct {
	gorm.Model
	CountTypes      int32
	Covered         int32
	CreatedAt       *time.Time
	DeletedAt       *time.Time
	Dominant        *TypePlantORM `gorm:"foreignKey:DominantId;references:Id"`
	DominantId      *string
	Id              string `gorm:"type:uuid;primaryKey"`
	Rating          int32
	Square          int32
	SquareTrialSite int32
	SubDominant     *TypePlantORM `gorm:"foreignKey:SubDominantId;references:Id"`
	SubDominantId   *string
	Title           string
	TrialSite       []*TrialSiteORM `gorm:"foreignKey:TransectId;references:Id"`
	UpdatedAt       *time.Time
	UserId          *string `gorm:"type:uuid;foreignKey:auth.User"`
}

// TableName overrides the default tablename generated by GORM
func (TransectORM) TableName() string {
	return "transects"
}

// ToORM runs the BeforeToORM hook if present, converts the fields of this
// object to ORM format, runs the AfterToORM hook, then returns the ORM object
func (m *Transect) ToORM(ctx context.Context) (TransectORM, error) {
	to := TransectORM{}
	var err error
	if prehook, ok := interface{}(m).(TransectWithBeforeToORM); ok {
		if err = prehook.BeforeToORM(ctx, &to); err != nil {
			return to, err
		}
	}
	if v, err := resource.Decode(&Transect{}, m.Id); err != nil {
		return to, err
	} else if v != nil {
		to.Id = v.(string)
	}
	to.Title = m.Title
	to.Covered = m.Covered
	to.Rating = m.Rating
	to.Square = m.Square
	to.SquareTrialSite = m.SquareTrialSite
	to.CountTypes = m.CountTypes
	for _, v := range m.TrialSite {
		if v != nil {
			if tempTrialSite, cErr := v.ToORM(ctx); cErr == nil {
				to.TrialSite = append(to.TrialSite, &tempTrialSite)
			} else {
				return to, cErr
			}
		} else {
			to.TrialSite = append(to.TrialSite, nil)
		}
	}
	if m.Dominant != nil {
		tempDominant, err := m.Dominant.ToORM(ctx)
		if err != nil {
			return to, err
		}
		to.Dominant = &tempDominant
	}
	if m.SubDominant != nil {
		tempSubDominant, err := m.SubDominant.ToORM(ctx)
		if err != nil {
			return to, err
		}
		to.SubDominant = &tempSubDominant
	}
	if m.CreatedAt != nil {
		t := m.CreatedAt.AsTime()
		to.CreatedAt = &t
	}
	if m.UpdatedAt != nil {
		t := m.UpdatedAt.AsTime()
		to.UpdatedAt = &t
	}
	if m.DeletedAt != nil {
		t := m.DeletedAt.AsTime()
		to.DeletedAt = &t
	}
	if m.UserId != nil {
		if v, err := resource.Decode(nil, m.UserId); err != nil {
			return to, err
		} else if v != nil {
			vv := v.(string)
			to.UserId = &vv
		}
	}
	if posthook, ok := interface{}(m).(TransectWithAfterToORM); ok {
		err = posthook.AfterToORM(ctx, &to)
	}
	return to, err
}

// ToPB runs the BeforeToPB hook if present, converts the fields of this
// object to PB format, runs the AfterToPB hook, then returns the PB object
func (m *TransectORM) ToPB(ctx context.Context) (Transect, error) {
	to := Transect{}
	var err error
	if prehook, ok := interface{}(m).(TransectWithBeforeToPB); ok {
		if err = prehook.BeforeToPB(ctx, &to); err != nil {
			return to, err
		}
	}
	if v, err := resource.Encode(&Transect{}, m.Id); err != nil {
		return to, err
	} else {
		to.Id = v
	}
	to.Title = m.Title
	to.Covered = m.Covered
	to.Rating = m.Rating
	to.Square = m.Square
	to.SquareTrialSite = m.SquareTrialSite
	to.CountTypes = m.CountTypes
	for _, v := range m.TrialSite {
		if v != nil {
			if tempTrialSite, cErr := v.ToPB(ctx); cErr == nil {
				to.TrialSite = append(to.TrialSite, &tempTrialSite)
			} else {
				return to, cErr
			}
		} else {
			to.TrialSite = append(to.TrialSite, nil)
		}
	}
	if m.Dominant != nil {
		tempDominant, err := m.Dominant.ToPB(ctx)
		if err != nil {
			return to, err
		}
		to.Dominant = &tempDominant
	}
	if m.SubDominant != nil {
		tempSubDominant, err := m.SubDominant.ToPB(ctx)
		if err != nil {
			return to, err
		}
		to.SubDominant = &tempSubDominant
	}
	if m.CreatedAt != nil {
		to.CreatedAt = timestamppb.New(*m.CreatedAt)
	}
	if m.UpdatedAt != nil {
		to.UpdatedAt = timestamppb.New(*m.UpdatedAt)
	}
	if m.DeletedAt != nil {
		to.DeletedAt = timestamppb.New(*m.DeletedAt)
	}
	if m.UserId != nil {
		if v, err := resource.Encode(nil, *m.UserId); err != nil {
			return to, err
		} else {
			to.UserId = v
		}
	}
	if posthook, ok := interface{}(m).(TransectWithAfterToPB); ok {
		err = posthook.AfterToPB(ctx, &to)
	}
	return to, err
}

// The following are interfaces you can implement for special behavior during ORM/PB conversions
// of type Transect the arg will be the target, the caller the one being converted from

// TransectBeforeToORM called before default ToORM code
type TransectWithBeforeToORM interface {
	BeforeToORM(context.Context, *TransectORM) error
}

// TransectAfterToORM called after default ToORM code
type TransectWithAfterToORM interface {
	AfterToORM(context.Context, *TransectORM) error
}

// TransectBeforeToPB called before default ToPB code
type TransectWithBeforeToPB interface {
	BeforeToPB(context.Context, *Transect) error
}

// TransectAfterToPB called after default ToPB code
type TransectWithAfterToPB interface {
	AfterToPB(context.Context, *Transect) error
}

// DefaultCreateTransect executes a basic gorm create call
func DefaultCreateTransect(ctx context.Context, in *Transect, db *gorm.DB) (*Transect, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeCreate_); ok {
		if db, err = hook.BeforeCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Omit("SubDominant", "TrialSite", "Dominant").Preload("SubDominant").Preload("TrialSite").Preload("Dominant").Create(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithAfterCreate_); ok {
		if err = hook.AfterCreate_(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	return &pbResponse, err
}

type TransectORMWithBeforeCreate_ interface {
	BeforeCreate_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithAfterCreate_ interface {
	AfterCreate_(context.Context, *gorm.DB) error
}

func DefaultReadTransect(ctx context.Context, in *Transect, db *gorm.DB) (*Transect, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if ormObj.Id == "" {
		return nil, errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeReadApplyQuery); ok {
		if db, err = hook.BeforeReadApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeReadFind); ok {
		if db, err = hook.BeforeReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	ormResponse := TransectORM{}
	if err = db.Where(&ormObj).First(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormResponse).(TransectORMWithAfterReadFind); ok {
		if err = hook.AfterReadFind(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormResponse.ToPB(ctx)
	return &pbResponse, err
}

type TransectORMWithBeforeReadApplyQuery interface {
	BeforeReadApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithBeforeReadFind interface {
	BeforeReadFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithAfterReadFind interface {
	AfterReadFind(context.Context, *gorm.DB) error
}

func DefaultDeleteTransect(ctx context.Context, in *Transect, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return err
	}
	if ormObj.Id == "" {
		return errors.EmptyIdError
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeDelete_); ok {
		if db, err = hook.BeforeDelete_(ctx, db); err != nil {
			return err
		}
	}
	err = db.Where(&ormObj).Delete(&TransectORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithAfterDelete_); ok {
		err = hook.AfterDelete_(ctx, db)
	}
	return err
}

type TransectORMWithBeforeDelete_ interface {
	BeforeDelete_(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithAfterDelete_ interface {
	AfterDelete_(context.Context, *gorm.DB) error
}

func DefaultDeleteTransectSet(ctx context.Context, in []*Transect, db *gorm.DB) error {
	if in == nil {
		return errors.NilArgumentError
	}
	var err error
	keys := []string{}
	for _, obj := range in {
		ormObj, err := obj.ToORM(ctx)
		if err != nil {
			return err
		}
		if ormObj.Id == "" {
			return errors.EmptyIdError
		}
		keys = append(keys, ormObj.Id)
	}
	if hook, ok := (interface{}(&TransectORM{})).(TransectORMWithBeforeDeleteSet); ok {
		if db, err = hook.BeforeDeleteSet(ctx, in, db); err != nil {
			return err
		}
	}
	err = db.Where("id in (?)", keys).Delete(&TransectORM{}).Error
	if err != nil {
		return err
	}
	if hook, ok := (interface{}(&TransectORM{})).(TransectORMWithAfterDeleteSet); ok {
		err = hook.AfterDeleteSet(ctx, in, db)
	}
	return err
}

type TransectORMWithBeforeDeleteSet interface {
	BeforeDeleteSet(context.Context, []*Transect, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithAfterDeleteSet interface {
	AfterDeleteSet(context.Context, []*Transect, *gorm.DB) error
}

// DefaultStrictUpdateTransect clears / replaces / appends first level 1:many children and then executes a gorm update call
func DefaultStrictUpdateTransect(ctx context.Context, in *Transect, db *gorm.DB) (*Transect, error) {
	if in == nil {
		return nil, fmt.Errorf("Nil argument to DefaultStrictUpdateTransect")
	}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	lockedRow := &TransectORM{}
	db.Model(&ormObj).Set("gorm:query_option", "FOR UPDATE").Where("id=?", ormObj.Id).First(lockedRow)
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeStrictUpdateCleanup); ok {
		if db, err = hook.BeforeStrictUpdateCleanup(ctx, db); err != nil {
			return nil, err
		}
	}
	filterTrialSite := TrialSiteORM{}
	if ormObj.Id == "" {
		return nil, errors.EmptyIdError
	}
	filterTrialSite.TransectId = new(string)
	*filterTrialSite.TransectId = ormObj.Id
	if err = db.Where(filterTrialSite).Delete(TrialSiteORM{}).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeStrictUpdateSave); ok {
		if db, err = hook.BeforeStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	if err = db.Omit("Dominant", "SubDominant", "TrialSite").Preload("SubDominant").Preload("TrialSite").Preload("Dominant").Save(&ormObj).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithAfterStrictUpdateSave); ok {
		if err = hook.AfterStrictUpdateSave(ctx, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := ormObj.ToPB(ctx)
	if err != nil {
		return nil, err
	}
	return &pbResponse, err
}

type TransectORMWithBeforeStrictUpdateCleanup interface {
	BeforeStrictUpdateCleanup(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithBeforeStrictUpdateSave interface {
	BeforeStrictUpdateSave(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithAfterStrictUpdateSave interface {
	AfterStrictUpdateSave(context.Context, *gorm.DB) error
}

// DefaultPatchTransect executes a basic gorm update call with patch behavior
func DefaultPatchTransect(ctx context.Context, in *Transect, updateMask *field_mask.FieldMask, db *gorm.DB) (*Transect, error) {
	if in == nil {
		return nil, errors.NilArgumentError
	}
	var pbObj Transect
	var err error
	if hook, ok := interface{}(&pbObj).(TransectWithBeforePatchRead); ok {
		if db, err = hook.BeforePatchRead(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbReadRes, err := DefaultReadTransect(ctx, &Transect{Id: in.GetId()}, db)
	if err != nil {
		return nil, err
	}
	pbObj = *pbReadRes
	if hook, ok := interface{}(&pbObj).(TransectWithBeforePatchApplyFieldMask); ok {
		if db, err = hook.BeforePatchApplyFieldMask(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	if _, err := DefaultApplyFieldMaskTransect(ctx, &pbObj, in, updateMask, "", db); err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&pbObj).(TransectWithBeforePatchSave); ok {
		if db, err = hook.BeforePatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	pbResponse, err := DefaultStrictUpdateTransect(ctx, &pbObj, db)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(pbResponse).(TransectWithAfterPatchSave); ok {
		if err = hook.AfterPatchSave(ctx, in, updateMask, db); err != nil {
			return nil, err
		}
	}
	return pbResponse, nil
}

type TransectWithBeforePatchRead interface {
	BeforePatchRead(context.Context, *Transect, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type TransectWithBeforePatchApplyFieldMask interface {
	BeforePatchApplyFieldMask(context.Context, *Transect, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type TransectWithBeforePatchSave interface {
	BeforePatchSave(context.Context, *Transect, *field_mask.FieldMask, *gorm.DB) (*gorm.DB, error)
}
type TransectWithAfterPatchSave interface {
	AfterPatchSave(context.Context, *Transect, *field_mask.FieldMask, *gorm.DB) error
}

// DefaultPatchSetTransect executes a bulk gorm update call with patch behavior
func DefaultPatchSetTransect(ctx context.Context, objects []*Transect, updateMasks []*field_mask.FieldMask, db *gorm.DB) ([]*Transect, error) {
	if len(objects) != len(updateMasks) {
		return nil, fmt.Errorf(errors.BadRepeatedFieldMaskTpl, len(updateMasks), len(objects))
	}

	results := make([]*Transect, 0, len(objects))
	for i, patcher := range objects {
		pbResponse, err := DefaultPatchTransect(ctx, patcher, updateMasks[i], db)
		if err != nil {
			return nil, err
		}

		results = append(results, pbResponse)
	}

	return results, nil
}

// DefaultApplyFieldMaskTransect patches an pbObject with patcher according to a field mask.
func DefaultApplyFieldMaskTransect(ctx context.Context, patchee *Transect, patcher *Transect, updateMask *field_mask.FieldMask, prefix string, db *gorm.DB) (*Transect, error) {
	if patcher == nil {
		return nil, nil
	} else if patchee == nil {
		return nil, errors.NilArgumentError
	}
	var err error
	var updatedDominant bool
	var updatedSubDominant bool
	var updatedCreatedAt bool
	var updatedUpdatedAt bool
	var updatedDeletedAt bool
	for i, f := range updateMask.Paths {
		if f == prefix+"Id" {
			patchee.Id = patcher.Id
			continue
		}
		if f == prefix+"Title" {
			patchee.Title = patcher.Title
			continue
		}
		if f == prefix+"Covered" {
			patchee.Covered = patcher.Covered
			continue
		}
		if f == prefix+"Rating" {
			patchee.Rating = patcher.Rating
			continue
		}
		if f == prefix+"Square" {
			patchee.Square = patcher.Square
			continue
		}
		if f == prefix+"SquareTrialSite" {
			patchee.SquareTrialSite = patcher.SquareTrialSite
			continue
		}
		if f == prefix+"CountTypes" {
			patchee.CountTypes = patcher.CountTypes
			continue
		}
		if f == prefix+"TrialSite" {
			patchee.TrialSite = patcher.TrialSite
			continue
		}
		if !updatedDominant && strings.HasPrefix(f, prefix+"Dominant.") {
			updatedDominant = true
			if patcher.Dominant == nil {
				patchee.Dominant = nil
				continue
			}
			if patchee.Dominant == nil {
				patchee.Dominant = &TypePlant{}
			}
			if o, err := DefaultApplyFieldMaskTypePlant(ctx, patchee.Dominant, patcher.Dominant, &field_mask.FieldMask{Paths: updateMask.Paths[i:]}, prefix+"Dominant.", db); err != nil {
				return nil, err
			} else {
				patchee.Dominant = o
			}
			continue
		}
		if f == prefix+"Dominant" {
			updatedDominant = true
			patchee.Dominant = patcher.Dominant
			continue
		}
		if !updatedSubDominant && strings.HasPrefix(f, prefix+"SubDominant.") {
			updatedSubDominant = true
			if patcher.SubDominant == nil {
				patchee.SubDominant = nil
				continue
			}
			if patchee.SubDominant == nil {
				patchee.SubDominant = &TypePlant{}
			}
			if o, err := DefaultApplyFieldMaskTypePlant(ctx, patchee.SubDominant, patcher.SubDominant, &field_mask.FieldMask{Paths: updateMask.Paths[i:]}, prefix+"SubDominant.", db); err != nil {
				return nil, err
			} else {
				patchee.SubDominant = o
			}
			continue
		}
		if f == prefix+"SubDominant" {
			updatedSubDominant = true
			patchee.SubDominant = patcher.SubDominant
			continue
		}
		if !updatedCreatedAt && strings.HasPrefix(f, prefix+"CreatedAt.") {
			if patcher.CreatedAt == nil {
				patchee.CreatedAt = nil
				continue
			}
			if patchee.CreatedAt == nil {
				patchee.CreatedAt = &timestamppb.Timestamp{}
			}
			childMask := &field_mask.FieldMask{}
			for j := i; j < len(updateMask.Paths); j++ {
				if trimPath := strings.TrimPrefix(updateMask.Paths[j], prefix+"CreatedAt."); trimPath != updateMask.Paths[j] {
					childMask.Paths = append(childMask.Paths, trimPath)
				}
			}
			if err := gorm1.MergeWithMask(patcher.CreatedAt, patchee.CreatedAt, childMask); err != nil {
				return nil, nil
			}
		}
		if f == prefix+"CreatedAt" {
			updatedCreatedAt = true
			patchee.CreatedAt = patcher.CreatedAt
			continue
		}
		if !updatedUpdatedAt && strings.HasPrefix(f, prefix+"UpdatedAt.") {
			if patcher.UpdatedAt == nil {
				patchee.UpdatedAt = nil
				continue
			}
			if patchee.UpdatedAt == nil {
				patchee.UpdatedAt = &timestamppb.Timestamp{}
			}
			childMask := &field_mask.FieldMask{}
			for j := i; j < len(updateMask.Paths); j++ {
				if trimPath := strings.TrimPrefix(updateMask.Paths[j], prefix+"UpdatedAt."); trimPath != updateMask.Paths[j] {
					childMask.Paths = append(childMask.Paths, trimPath)
				}
			}
			if err := gorm1.MergeWithMask(patcher.UpdatedAt, patchee.UpdatedAt, childMask); err != nil {
				return nil, nil
			}
		}
		if f == prefix+"UpdatedAt" {
			updatedUpdatedAt = true
			patchee.UpdatedAt = patcher.UpdatedAt
			continue
		}
		if !updatedDeletedAt && strings.HasPrefix(f, prefix+"DeletedAt.") {
			if patcher.DeletedAt == nil {
				patchee.DeletedAt = nil
				continue
			}
			if patchee.DeletedAt == nil {
				patchee.DeletedAt = &timestamppb.Timestamp{}
			}
			childMask := &field_mask.FieldMask{}
			for j := i; j < len(updateMask.Paths); j++ {
				if trimPath := strings.TrimPrefix(updateMask.Paths[j], prefix+"DeletedAt."); trimPath != updateMask.Paths[j] {
					childMask.Paths = append(childMask.Paths, trimPath)
				}
			}
			if err := gorm1.MergeWithMask(patcher.DeletedAt, patchee.DeletedAt, childMask); err != nil {
				return nil, nil
			}
		}
		if f == prefix+"DeletedAt" {
			updatedDeletedAt = true
			patchee.DeletedAt = patcher.DeletedAt
			continue
		}
		if f == prefix+"UserId" {
			patchee.UserId = patcher.UserId
			continue
		}
	}
	if err != nil {
		return nil, err
	}
	return patchee, nil
}

// DefaultListTransect executes a gorm list call
func DefaultListTransect(ctx context.Context, db *gorm.DB) ([]*Transect, error) {
	in := Transect{}
	ormObj, err := in.ToORM(ctx)
	if err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeListApplyQuery); ok {
		if db, err = hook.BeforeListApplyQuery(ctx, db); err != nil {
			return nil, err
		}
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithBeforeListFind); ok {
		if db, err = hook.BeforeListFind(ctx, db); err != nil {
			return nil, err
		}
	}
	db = db.Where(&ormObj)
	db = db.Order("id")
	ormResponse := []TransectORM{}
	if err := db.Find(&ormResponse).Error; err != nil {
		return nil, err
	}
	if hook, ok := interface{}(&ormObj).(TransectORMWithAfterListFind); ok {
		if err = hook.AfterListFind(ctx, db, &ormResponse); err != nil {
			return nil, err
		}
	}
	pbResponse := []*Transect{}
	for _, responseEntry := range ormResponse {
		temp, err := responseEntry.ToPB(ctx)
		if err != nil {
			return nil, err
		}
		pbResponse = append(pbResponse, &temp)
	}
	return pbResponse, nil
}

type TransectORMWithBeforeListApplyQuery interface {
	BeforeListApplyQuery(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithBeforeListFind interface {
	BeforeListFind(context.Context, *gorm.DB) (*gorm.DB, error)
}
type TransectORMWithAfterListFind interface {
	AfterListFind(context.Context, *gorm.DB, *[]TransectORM) error
}
