// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: trial-site.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TrialSiteServiceClient is the client API for TrialSiteService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TrialSiteServiceClient interface {
	CreateTrialSite(ctx context.Context, in *InputTrialSiteRequest, opts ...grpc.CallOption) (*TrialSite, error)
	// Получение сущности по id
	GetTrialSite(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*TrialSite, error)
	// Обновление сущности по id
	UpTrialSite(ctx context.Context, in *InputTrialSiteRequest, opts ...grpc.CallOption) (*TrialSite, error)
	// Обновление сущности по id
	AddPlantsToTrialSite(ctx context.Context, in *InputTrialSiteRequest, opts ...grpc.CallOption) (*TrialSite, error)
	// Удаление сущности по заголовку
	DeleteTrialSite(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Получение списка всех сущностей
	GetAllTrialSite(ctx context.Context, in *PagesRequest, opts ...grpc.CallOption) (*TrialSiteList, error)
	CreatePlant(ctx context.Context, in *InputPlantRequest, opts ...grpc.CallOption) (*Plant, error)
	// Получение сущности по id
	GetPlant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Plant, error)
	// Обновление сущности по id
	UpdatePlant(ctx context.Context, in *InputPlantRequest, opts ...grpc.CallOption) (*Plant, error)
	// Удаление сущности по заголовку
	DeletePlant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BoolResponse, error)
	// Получение списка всех сущностей
	GetAllPlant(ctx context.Context, in *PagesRequest, opts ...grpc.CallOption) (*PlantList, error)
}

type trialSiteServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTrialSiteServiceClient(cc grpc.ClientConnInterface) TrialSiteServiceClient {
	return &trialSiteServiceClient{cc}
}

func (c *trialSiteServiceClient) CreateTrialSite(ctx context.Context, in *InputTrialSiteRequest, opts ...grpc.CallOption) (*TrialSite, error) {
	out := new(TrialSite)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/CreateTrialSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) GetTrialSite(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*TrialSite, error) {
	out := new(TrialSite)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/GetTrialSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) UpTrialSite(ctx context.Context, in *InputTrialSiteRequest, opts ...grpc.CallOption) (*TrialSite, error) {
	out := new(TrialSite)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/UpTrialSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) AddPlantsToTrialSite(ctx context.Context, in *InputTrialSiteRequest, opts ...grpc.CallOption) (*TrialSite, error) {
	out := new(TrialSite)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/AddPlantsToTrialSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) DeleteTrialSite(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/DeleteTrialSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) GetAllTrialSite(ctx context.Context, in *PagesRequest, opts ...grpc.CallOption) (*TrialSiteList, error) {
	out := new(TrialSiteList)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/GetAllTrialSite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) CreatePlant(ctx context.Context, in *InputPlantRequest, opts ...grpc.CallOption) (*Plant, error) {
	out := new(Plant)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/CreatePlant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) GetPlant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*Plant, error) {
	out := new(Plant)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/GetPlant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) UpdatePlant(ctx context.Context, in *InputPlantRequest, opts ...grpc.CallOption) (*Plant, error) {
	out := new(Plant)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/UpdatePlant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) DeletePlant(ctx context.Context, in *IdRequest, opts ...grpc.CallOption) (*BoolResponse, error) {
	out := new(BoolResponse)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/DeletePlant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *trialSiteServiceClient) GetAllPlant(ctx context.Context, in *PagesRequest, opts ...grpc.CallOption) (*PlantList, error) {
	out := new(PlantList)
	err := c.cc.Invoke(ctx, "/botany.TrialSiteService/GetAllPlant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrialSiteServiceServer is the server API for TrialSiteService service.
// All implementations must embed UnimplementedTrialSiteServiceServer
// for forward compatibility
type TrialSiteServiceServer interface {
	CreateTrialSite(context.Context, *InputTrialSiteRequest) (*TrialSite, error)
	// Получение сущности по id
	GetTrialSite(context.Context, *IdRequest) (*TrialSite, error)
	// Обновление сущности по id
	UpTrialSite(context.Context, *InputTrialSiteRequest) (*TrialSite, error)
	// Обновление сущности по id
	AddPlantsToTrialSite(context.Context, *InputTrialSiteRequest) (*TrialSite, error)
	// Удаление сущности по заголовку
	DeleteTrialSite(context.Context, *IdRequest) (*BoolResponse, error)
	// Получение списка всех сущностей
	GetAllTrialSite(context.Context, *PagesRequest) (*TrialSiteList, error)
	CreatePlant(context.Context, *InputPlantRequest) (*Plant, error)
	// Получение сущности по id
	GetPlant(context.Context, *IdRequest) (*Plant, error)
	// Обновление сущности по id
	UpdatePlant(context.Context, *InputPlantRequest) (*Plant, error)
	// Удаление сущности по заголовку
	DeletePlant(context.Context, *IdRequest) (*BoolResponse, error)
	// Получение списка всех сущностей
	GetAllPlant(context.Context, *PagesRequest) (*PlantList, error)
	MustEmbedUnimplementedTrialSiteServiceServer()
}

// UnimplementedTrialSiteServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTrialSiteServiceServer struct {
}

func (UnimplementedTrialSiteServiceServer) CreateTrialSite(context.Context, *InputTrialSiteRequest) (*TrialSite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTrialSite not implemented")
}
func (UnimplementedTrialSiteServiceServer) GetTrialSite(context.Context, *IdRequest) (*TrialSite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTrialSite not implemented")
}
func (UnimplementedTrialSiteServiceServer) UpTrialSite(context.Context, *InputTrialSiteRequest) (*TrialSite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpTrialSite not implemented")
}
func (UnimplementedTrialSiteServiceServer) AddPlantsToTrialSite(context.Context, *InputTrialSiteRequest) (*TrialSite, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddPlantsToTrialSite not implemented")
}
func (UnimplementedTrialSiteServiceServer) DeleteTrialSite(context.Context, *IdRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTrialSite not implemented")
}
func (UnimplementedTrialSiteServiceServer) GetAllTrialSite(context.Context, *PagesRequest) (*TrialSiteList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllTrialSite not implemented")
}
func (UnimplementedTrialSiteServiceServer) CreatePlant(context.Context, *InputPlantRequest) (*Plant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePlant not implemented")
}
func (UnimplementedTrialSiteServiceServer) GetPlant(context.Context, *IdRequest) (*Plant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlant not implemented")
}
func (UnimplementedTrialSiteServiceServer) UpdatePlant(context.Context, *InputPlantRequest) (*Plant, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlant not implemented")
}
func (UnimplementedTrialSiteServiceServer) DeletePlant(context.Context, *IdRequest) (*BoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePlant not implemented")
}
func (UnimplementedTrialSiteServiceServer) GetAllPlant(context.Context, *PagesRequest) (*PlantList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPlant not implemented")
}
func (UnimplementedTrialSiteServiceServer) MustEmbedUnimplementedTrialSiteServiceServer() {}

// UnsafeTrialSiteServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TrialSiteServiceServer will
// result in compilation errors.
type UnsafeTrialSiteServiceServer interface {
	MustEmbedUnimplementedTrialSiteServiceServer()
}

func RegisterTrialSiteServiceServer(s grpc.ServiceRegistrar, srv TrialSiteServiceServer) {
	s.RegisterService(&TrialSiteService_ServiceDesc, srv)
}

func _TrialSiteService_CreateTrialSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputTrialSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).CreateTrialSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/CreateTrialSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).CreateTrialSite(ctx, req.(*InputTrialSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_GetTrialSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).GetTrialSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/GetTrialSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).GetTrialSite(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_UpTrialSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputTrialSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).UpTrialSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/UpTrialSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).UpTrialSite(ctx, req.(*InputTrialSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_AddPlantsToTrialSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputTrialSiteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).AddPlantsToTrialSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/AddPlantsToTrialSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).AddPlantsToTrialSite(ctx, req.(*InputTrialSiteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_DeleteTrialSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).DeleteTrialSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/DeleteTrialSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).DeleteTrialSite(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_GetAllTrialSite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).GetAllTrialSite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/GetAllTrialSite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).GetAllTrialSite(ctx, req.(*PagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_CreatePlant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputPlantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).CreatePlant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/CreatePlant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).CreatePlant(ctx, req.(*InputPlantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_GetPlant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).GetPlant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/GetPlant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).GetPlant(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_UpdatePlant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputPlantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).UpdatePlant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/UpdatePlant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).UpdatePlant(ctx, req.(*InputPlantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_DeletePlant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).DeletePlant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/DeletePlant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).DeletePlant(ctx, req.(*IdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TrialSiteService_GetAllPlant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrialSiteServiceServer).GetAllPlant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/botany.TrialSiteService/GetAllPlant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrialSiteServiceServer).GetAllPlant(ctx, req.(*PagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TrialSiteService_ServiceDesc is the grpc.ServiceDesc for TrialSiteService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TrialSiteService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "botany.TrialSiteService",
	HandlerType: (*TrialSiteServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrialSite",
			Handler:    _TrialSiteService_CreateTrialSite_Handler,
		},
		{
			MethodName: "GetTrialSite",
			Handler:    _TrialSiteService_GetTrialSite_Handler,
		},
		{
			MethodName: "UpTrialSite",
			Handler:    _TrialSiteService_UpTrialSite_Handler,
		},
		{
			MethodName: "AddPlantsToTrialSite",
			Handler:    _TrialSiteService_AddPlantsToTrialSite_Handler,
		},
		{
			MethodName: "DeleteTrialSite",
			Handler:    _TrialSiteService_DeleteTrialSite_Handler,
		},
		{
			MethodName: "GetAllTrialSite",
			Handler:    _TrialSiteService_GetAllTrialSite_Handler,
		},
		{
			MethodName: "CreatePlant",
			Handler:    _TrialSiteService_CreatePlant_Handler,
		},
		{
			MethodName: "GetPlant",
			Handler:    _TrialSiteService_GetPlant_Handler,
		},
		{
			MethodName: "UpdatePlant",
			Handler:    _TrialSiteService_UpdatePlant_Handler,
		},
		{
			MethodName: "DeletePlant",
			Handler:    _TrialSiteService_DeletePlant_Handler,
		},
		{
			MethodName: "GetAllPlant",
			Handler:    _TrialSiteService_GetAllPlant_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "trial-site.proto",
}
