package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/sergey23144V/BotanyBackend/servers/g-rpc/api"
	"github.com/sergey23144V/BotanyBackend/servers/graphql/graph/model"
)

// TypeAnalysis is the resolver for the typeAnalysis field.
func (r *analysisResolver) TypeAnalysis(ctx context.Context, obj *api.Analysis) (model.TypeAnalysis, error) {
	panic(fmt.Errorf("not implemented: TypeAnalysis - typeAnalysis"))
}

// CreatAnalysis is the resolver for the creatAnalysis field.
func (r *analysisMutationResolver) CreatAnalysis(ctx context.Context, obj *model.AnalysisMutation, input *api.InputCreateAnalysis) (*api.Ecomorph, error) {
	panic(fmt.Errorf("not implemented: CreatAnalysis - creatAnalysis"))
}

// RepeatedAnalysis is the resolver for the repeatedAnalysis field.
func (r *analysisMutationResolver) RepeatedAnalysis(ctx context.Context, obj *model.AnalysisMutation, input *api.InputUpdateAnalysis) (*api.Ecomorph, error) {
	panic(fmt.Errorf("not implemented: RepeatedAnalysis - repeatedAnalysis"))
}

// DeleteAnalysis is the resolver for the deleteAnalysis field.
func (r *analysisMutationResolver) DeleteAnalysis(ctx context.Context, obj *model.AnalysisMutation, id string) (*api.BoolResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteAnalysis - deleteAnalysis"))
}

// GetAnalysis is the resolver for the getAnalysis field.
func (r *analysisQueryResolver) GetAnalysis(ctx context.Context, obj *model.AnalysisQuery, id string) (*api.Ecomorph, error) {
	panic(fmt.Errorf("not implemented: GetAnalysis - getAnalysis"))
}

// GetListAnalysis is the resolver for the getListAnalysis field.
func (r *analysisQueryResolver) GetListAnalysis(ctx context.Context, obj *model.AnalysisQuery, pages *api.PagesRequest) (*api.EcomorphsList, error) {
	panic(fmt.Errorf("not implemented: GetListAnalysis - getListAnalysis"))
}

// TypeAnalysis is the resolver for the typeAnalysis field.
func (r *analysisInputResolver) TypeAnalysis(ctx context.Context, obj *api.Analysis, data model.TypeAnalysis) error {
	panic(fmt.Errorf("not implemented: TypeAnalysis - typeAnalysis"))
}

// Analysis returns AnalysisResolver implementation.
func (r *Resolver) Analysis() AnalysisResolver { return &analysisResolver{r} }

// AnalysisMutation returns AnalysisMutationResolver implementation.
func (r *Resolver) AnalysisMutation() AnalysisMutationResolver { return &analysisMutationResolver{r} }

// AnalysisQuery returns AnalysisQueryResolver implementation.
func (r *Resolver) AnalysisQuery() AnalysisQueryResolver { return &analysisQueryResolver{r} }

// AnalysisInput returns AnalysisInputResolver implementation.
func (r *Resolver) AnalysisInput() AnalysisInputResolver { return &analysisInputResolver{r} }

type analysisResolver struct{ *Resolver }
type analysisMutationResolver struct{ *Resolver }
type analysisQueryResolver struct{ *Resolver }
type analysisInputResolver struct{ *Resolver }
