package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/sergey23144V/BotanyBackend/servers/g-rpc/api"
	"github.com/sergey23144V/BotanyBackend/servers/graphql/graph/model"
)

// SignUpUser is the resolver for the signUpUser field.
func (r *authMutationResolver) SignUpUser(ctx context.Context, obj *model.AuthMutation, data *api.SignUpUserInput) (*api.SignInUserResponse, error) {
	return r.AuthServerImpl.SignUpUser(ctx, data)
}

// SignInUser is the resolver for the signInUser field.
func (r *authMutationResolver) SignInUser(ctx context.Context, obj *model.AuthMutation, data *api.SignInUserInput) (*api.SignInUserResponse, error) {
	return r.AuthServerImpl.SignInUser(ctx, data)
}

// AuthMutation returns AuthMutationResolver implementation.
func (r *Resolver) AuthMutation() AuthMutationResolver { return &authMutationResolver{r} }

type authMutationResolver struct{ *Resolver }
