package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"

	"github.com/sergey23144V/BotanyBackend/servers/g-rpc/api"
	"github.com/sergey23144V/BotanyBackend/servers/graphql/graph/model"
)

// GetImgByID is the resolver for the getImgByID field.
func (r *imgQueryResolver) GetImgByID(ctx context.Context, obj *model.ImgQuery, id string) (*api.Img, error) {
	return r.service.GetImgByID(ctx, ToIdRequest(id))
}

// GetListImg is the resolver for the getListImg field.
func (r *imgQueryResolver) GetListImg(ctx context.Context, obj *model.ImgQuery, pages *api.PagesRequest) (*api.ImgList, error) {
	return r.service.GetListImg(ctx, pages)
}

// ImgQuery returns ImgQueryResolver implementation.
func (r *Resolver) ImgQuery() ImgQueryResolver { return &imgQueryResolver{r} }

type imgQueryResolver struct{ *Resolver }
