// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/sergey23144V/BotanyBackend/servers/g-rpc/api"
)

type AuthMutation struct {
	SignUpUser *api.SignInUserResponse `json:"signUpUser,omitempty"`
	SignInUser *api.SignInUserResponse `json:"signInUser,omitempty"`
}

type EcomorphMutation struct {
	InsertEcomorph     *api.Ecomorph     `json:"insertEcomorph"`
	UpdateEcomorph     *api.Ecomorph     `json:"updateEcomorph"`
	DeleteEcomorphByID *api.BoolResponse `json:"deleteEcomorphById"`
}

type EcomorphQuery struct {
	GetEcomorphByID *api.Ecomorph      `json:"getEcomorphById"`
	GetListEcomorph *api.EcomorphsList `json:"getListEcomorph"`
}

type EcomorphsEntityMutation struct {
	InsertEcomorphEntity     *api.EcomorphsEntity `json:"insertEcomorphEntity,omitempty"`
	UpdateEcomorphEntity     *api.EcomorphsEntity `json:"updateEcomorphEntity,omitempty"`
	DeleteEcomorphEntityByID *api.BoolResponse    `json:"deleteEcomorphEntityByID,omitempty"`
}

type EcomorphsEntityQuery struct {
	GetEcomorphEntityByID *api.EcomorphsEntity     `json:"getEcomorphEntityByID,omitempty"`
	GetAllEcomorphEntity  *api.EcomorphsEntityList `json:"getAllEcomorphEntity,omitempty"`
}

type IDRequest struct {
	ID string `json:"id"`
}

type Mutation struct {
}

type Query struct {
}

type TransectMutation struct {
	CreateTransect *api.Transect     `json:"createTransect,omitempty"`
	UpTransect     *api.Transect     `json:"upTransect,omitempty"`
	DeleteTransect *api.BoolResponse `json:"deleteTransect,omitempty"`
}

type TransectQuery struct {
	GetTransect    *api.Transect     `json:"getTransect,omitempty"`
	GetAllTransect *api.TransectList `json:"getAllTransect,omitempty"`
}

type TrialSiteMutation struct {
	CreateTrialSite *api.TrialSite    `json:"createTrialSite,omitempty"`
	UpTrialSite     *api.TrialSite    `json:"upTrialSite,omitempty"`
	DeleteTrialSite *api.BoolResponse `json:"deleteTrialSite,omitempty"`
}

type TrialSiteQuery struct {
	GetTrialSite    *api.TrialSite     `json:"getTrialSite,omitempty"`
	GetAllTrialSite *api.TrialSiteList `json:"getAllTrialSite,omitempty"`
}

type TypePlantMutation struct {
	CreateTypePlant *api.TypePlant    `json:"createTypePlant,omitempty"`
	UpdateTypePlant *api.TypePlant    `json:"updateTypePlant,omitempty"`
	DeleteTypePlant *api.BoolResponse `json:"deleteTypePlant,omitempty"`
}

type TypePlantQuery struct {
	GetTypePlant    *api.TypePlant     `json:"getTypePlant,omitempty"`
	GetAllTypePlant *api.TypePlantList `json:"getAllTypePlant,omitempty"`
}
